# config_file
# Initial Takeoff 

start:
  spx: 0.0 # X Coord of Takeoff Position
  spy: 0.0 # Y Coord of Takeoff Position
  spz: -0.25 # Vehicle Initial Height
  spyaw: 1.57 # Yaw of Takeoff Position
  
  #tethered flight start position
  # spx: 0.43
  # spy: -2.03
  # spz: -0.25
  # spyaw: 1.57

# Command

command:
    mx: 4 # Max X coordinate
    my: 4 # Max Y coordinate
    mz: 4 # Max height
    ms: 0.3 #Max speed - distance (m) of setpoint away from current position
    cr: 0.01 #Rate of Change of setpoints
    
    ooct: 300 # number of seconds needed before resetting setpoint when out of control
    rh: -0.1 # hover height on return
    kh: -0.15 # max height permitted to kill power

# Hover trajectory
hover:
  hx: 0.0 # hover x pose
  hy: 0.0 # hover y pose
  hz: -0.2 # hover z pose
  hyaw: 1.57 # hover yaw pose


# Square trajectory 
square:
  speed: 0.3 # meters in front of drone to send setpoint (speed)
  hheight: -0.2 # hover height above ground
  side_length_x: 1.5 # Length of x side of the square
  side_length_y: 1.0 # Length of x side of the square

# Circle trajectory 
circle:
  speed: 0.2 # meters in front of drone to send setpoint (speed)
  hheight: -0.2 # hover height above ground
  radius: 1 # Radius of the circle
  num_loops: 1 # Number of loops

# Helix trajectory 
helix:
  hspeed: 0.25 # meters in front of drone to send setpoint (horizontal)
  vspeed: 0.01 # meters in front of drone to send setpoint (vertical)
  hheight: -0.2 # hover height above ground
  radius: 1.0 # Radius of the helix circle
  height: 0.5 # Vertical distance covered in each loop
  num_loops: 2 # Number of loops in the helix going up

linear_setpoints:
  speed: 0.4 # meters in front of drone to send setpoint
  hheight: -0.2 # hover height above ground
  num_setpoints: 15 # number of random setpoints
  random_yn: 0 # 1 for random setpoints, 0 for set setpoints
  random_setpoint_boundary:
    mx: 2 # Max X coordinate
    my: 2 # Max Y coordinate
    mz: 4 # Max height
  setpoints: # write setpoints here
  - [0.0, 0.0, 0.0, 0.0] # 1 Origin
  - [0.0, 0.0, -1.5, 0.0] # 2 Origin
  - [-1.5, -0.5, -0.0, 0.0] # 3
  - [-1.125, 0.5, -0.375, 0.0] # 4
  - [-0.75, -0.5, -0.75, 0.0] # 5
  - [0.0, -0.5, -1.5, 0.0] # 6
  - [0.0, 0.0, -1.5, 0.0] # 7
  - [-0.75, -0.25, -0.75, 0.0] # 8
  - [-0.75, 0.5, -0.75, 0.0] # 9
  - [0.75, 0.5, -2.25, 0.0] # 10
  - [0.1875, 0.0, -1.6875, 0.0] # 11
  - [0.75, -0.5, -2.25, 0.0] # 12
  - [1.125, -0.5, -2.625, 0.0] # 13
  - [1.5, 0.5, -3.0, 0.0] # 14
  - [1.5, 1.5, 0.0, 0.0] # 15

continuous_setpoints:
  speed: 0.4 # meters in front of drone to send setpoint
  hheight: -0.2 # hover height above ground
  time_of_flight: 30 # number of hundreds of setpoints



